### ISSUE TITLE
about the mean average precision (mAP) results for thumos14

### ISSUE THREAD

**Issue by Beatricehuihuihui** [dingfengshi/TriDet#11]
Hi, thanks for releasing the code! I reproduce directly for thumos14 dataset, but the mAP is  a bit lower than yours, below is the result. Do you know why this happens?
![last_ep_result](https://user-images.githubusercontent.com/34912230/236403664-84a6bdd6-8268-4925-abf3-335a218dd207.png)

**Comment by dingfengshi** [comment]
> Hi, thanks for releasing the code! I reproduce directly for thumos14 dataset, but the mAP is a bit lower than yours, below is the result. Do you know why this happens? ![last_ep_result](https://user-images.githubusercontent.com/34912230/236403664-84a6bdd6-8268-4925-abf3-335a218dd207.png)

Hi, it seems that different GPUs may produce different results. We conducted our experiments on different DGX-A100 machines and obtained the same results as those presented in our paper. We also tried a V100 GPU, which produced slightly lower results than the A100. There are similar phenomena in some other tasks. We don’t know the cause of the problem. It may be caused by the precision of different GPUs.

**Comment by ClancyAyres** [comment]
Hello, can I discuss with you the precautions when this code is reproduced, the mAP result on my side is lower

**Comment by Beatricehuihuihui** [comment]
> Hello, can I discuss with you the precautions when this code is reproduced, the mAP result on my side is lower

Hi, I don't change anything in the code , just run it on a Tesla V100 GPU.

**Comment by dingfengshi** [comment]
> > Hello, can I discuss with you the precautions when this code is reproduced, the mAP result on my side is lower
> 
> Hi, I don't change anything in the code , just run it on a Tesla V100 GPU.

Hi, I guess because the THUMOS dataset is relatively small and action intensive for each video, the result is more affected by GPU accuracy. Can you try training on a larger dataset (like HACS)? My experience is that this dataset is less sensitive to various parameters and may be less influenced by the device and environment.

**Comment by dingfengshi** [comment]
> Hello, can I discuss with you the precautions when this code is reproduced, the mAP result on my side is lower

Hi! feel free to email me your contact information to discuss this!
