### ISSUE TITLE
Suggestion for long videos training

### ISSUE THREAD

**Issue by lllllllll-3154** [dingfengshi/TriDet#24]
Do you have any parameters suggestion for those long videos whose segments have a long range and the video is also long? Thanks

**Comment by dingfengshi** [comment]
For this type of video, I guess you can try to extract a snippet feature in a low fps and large window size, or you can try to rescale the temporal feature to a fixed length like the setting of ActivityNet.

**Comment by lllllllll-3154** [comment]
Thanks so much for you answering. Does it mean the current configs and frameworks are more suitable for short segments with short videos, it is better to do some preprocess on the dataset?

**Comment by dingfengshi** [comment]
> Thanks so much for you answering. Does it mean the current configs and frameworks are more suitable for short segments with short videos, it is better to do some preprocess on the dataset?

Not really. Due to the diversity of videos, different optimization techniques are used for different types of video datasets. For instance, THUMOS14 contains very long videos (>30 min) with a lot of action instances and is typically implemented with a small window. On the other hand, ActivityNet has many videos with a lot of single long action instances and is often used in a rescaled way to improve performance. This would probably be a better initial configuration for the scenario you are referring to.
